-- ═══════════════════════════════════════════════════════════════
-- SEED WINE CATALOG — Vins de référence (données expert)
-- À exécuter dans Supabase → SQL Editor → New Query
-- ═══════════════════════════════════════════════════════════════

INSERT INTO wine_catalog (name, cuvee, region, appellation, color, robe, cepages, typical_alcohol, typical_price, peak_from, peak_to, aromas, pairings, service, estate)
VALUES
('Château Margaux','Grand Vin','Bordeaux','Margaux 1er Grand Cru Classé','rouge','#5A0E1A','[{"n":"Cabernet Sauvignon","p":87},{"n":"Merlot","p":8},{"n":"Petit Verdot","p":3},{"n":"Cabernet Franc","p":2}]',13.5,780,2030,2055,'["cassis","mûre","cerise noire","violette","cèdre","graphite","vanille","tabac"]','["Côte de bœuf","Agneau de Pauillac","Saint-nectaire affiné"]','{"temp":"17-18°","carafe":"Carafage 1h","verre":"Bordeaux XL"}','{"founded":1572,"owner":"Famille Mentzelopoulos","surface":"87 ha","terroir":"Graves günziennes profondes","desc":"Premier Grand Cru Classé en 1855, quintessence du Médoc."}'),

('Château Latour','Grand Vin','Bordeaux','Pauillac 1er Grand Cru Classé','rouge','#4A0C16','[{"n":"Cabernet Sauvignon","p":77},{"n":"Merlot","p":17},{"n":"Cabernet Franc","p":4},{"n":"Petit Verdot","p":2}]',13.5,900,2035,2060,'["cassis","mûre","réglisse","graphite","truffe","cèdre","tabac"]','["Côte de bœuf maturée","Agneau grillé","Cantal vieux"]','{"temp":"17-18°","carafe":"Carafage 2h","verre":"Bordeaux XL"}','{"founded":1331,"owner":"François Pinault (Artémis)","surface":"90 ha","terroir":"Graves profondes, L Enclos","desc":"Le plus puissant des Premiers Crus. A quitté les primeurs en 2012."}'),

('Château Lafite Rothschild','','Bordeaux','Pauillac 1er Grand Cru Classé','rouge','#580E1A','[{"n":"Cabernet Sauvignon","p":91},{"n":"Merlot","p":8.5},{"n":"Petit Verdot","p":0.5}]',13,800,2032,2060,'["cassis","groseille","violette","cèdre","graphite","vanille fine"]','["Carré d agneau","Canard rôti","Brie de Meaux"]','{"temp":"17-18°","carafe":"Carafage 1h","verre":"Bordeaux XL"}','{"founded":1234,"owner":"Famille Rothschild","surface":"112 ha","terroir":"Graves fines sur calcaire","desc":"L élégance bordelaise par excellence."}'),

('Château Ausone','','Bordeaux','Saint-Émilion 1er GCC A','rouge','#520E1A','[{"n":"Cabernet Franc","p":55},{"n":"Merlot","p":45}]',14,700,2032,2060,'["cerise noire","mûre","violette","réglisse","pierre calcaire","vanille"]','["Lièvre à la royale","Filet de bœuf","Parmigiano 36 mois"]','{"temp":"16-17°","carafe":"Carafage 1h30","verre":"Bordeaux XL"}','{"founded":350,"owner":"Famille Vauthier","surface":"7 ha","terroir":"Calcaire à astéries, coteau sud","desc":"Perché sur le plateau calcaire. L un des plus petits et anciens Premiers Crus A."}'),

('Château Rayas','','Rhône','Châteauneuf-du-Pape','rouge','#7A2030','[{"n":"Grenache","p":100}]',14.5,650,2028,2045,'["fraise confite","cerise kirsch","rose","cannelle","sous-bois","cuir fin"]','["Agneau de Sisteron","Rouget barbet","Picodon"]','{"temp":"15-16°","carafe":"Carafage léger","verre":"Bourgogne ballon"}','{"founded":1880,"owner":"Emmanuel Reynaud","surface":"13 ha","terroir":"Sables fins, exposition nord","desc":"Anti-conformiste : Grenache pur, exposition nord. Finesse unique."}'),

('M. Chapoutier','Le Méal','Rhône','Hermitage','rouge','#580E1C','[{"n":"Syrah","p":100}]',14,220,2028,2045,'["mûre","myrtille","olive noire","violette","poivre noir","chocolat"]','["Bœuf bourguignon","Aligot-saucisse","Fourme d Ambert"]','{"temp":"16-17°","carafe":"Carafage 1h","verre":"Syrah"}','{"founded":1808,"owner":"Michel Chapoutier","surface":"350 ha","terroir":"Granit et loess, Le Méal","desc":"Maison historique. Étiquettes en braille."}'),

('Domaine Alain Voge','Les Vieilles Vignes','Rhône','Cornas','rouge','#580F1C','[{"n":"Syrah","p":100}]',13.5,45,2028,2040,'["cassis","mûre","olive noire","violette","poivre","graphite","cuir"]','["Bœuf braisé","Saucisson","Saint-Nectaire"]','{"temp":"16-17°","carafe":"Carafage 45 min","verre":"Syrah"}','{"founded":1958,"owner":"Albéric Mazoyer","surface":"10 ha","terroir":"Granit décomposé, terrasses","desc":"Référence de Cornas. Vieilles vignes de 60+ ans sur granit."}'),

('Salon','Le Mesnil','Champagne','Champagne Grand Cru','effervescent','#DCC450','[{"n":"Chardonnay","p":100}]',12,650,2027,2045,'["citron confit","pomme verte","acacia","craie","pain grillé","noisette"]','["Oursin","Bar de ligne","Langoustine crue"]','{"temp":"10-12°","carafe":"Servir direct","verre":"Tulipe Champagne"}','{"founded":1911,"owner":"Laurent-Perrier","surface":"1 ha","terroir":"Craie à bélemnites, Le Mesnil-sur-Oger","desc":"Un seul vin, uniquement les grandes années. 37 millésimes depuis 1905."}'),

('Domaine Weinbach','Gewurztraminer Altenbourg SGN','Alsace','Alsace SGN','liquoreux','#C8951A','[{"n":"Gewurztraminer","p":100}]',12.5,120,2027,2050,'["litchi","mangue","fruit de la passion","rose turque","gingembre","miel"]','["Foie gras mi-cuit","Tarte au citron","Munster affiné"]','{"temp":"8-10°","carafe":"Servir direct","verre":"Tulipe étroite"}','{"founded":1612,"owner":"Famille Faller","surface":"30 ha","terroir":"Granit de Turkheim","desc":"Ancien domaine des Capucins. Pureté florale unique."}'),

('Domaine Josmeyer','Riesling Le Kottabe','Alsace','Alsace','blanc','#D8C248','[{"n":"Riesling","p":100}]',12.5,18,2026,2032,'["citron","pomme verte","pêche","tilleul","silex"]','["Choucroute garnie","Sandre","Munster jeune"]','{"temp":"10-12°","carafe":"Servir direct","verre":"Alsace tulipe"}','{"founded":1854,"owner":"Famille Meyer","surface":"27 ha","terroir":"Argilo-calcaire, Wintzenheim","desc":"Domaine historique. Rieslings secs et tendus, style gastronomique."}'),

('Clos Canarelli','Amphora','Corse','Corse Figari','rouge','#721C2A','[{"n":"Nielluccio","p":50},{"n":"Sciaccarellu","p":50}]',13.5,55,2027,2035,'["cerise","fraise","grenade","maquis en fleur","poivre","myrte","granit"]','["Veau corse aux olives","Figatellu","Brocciu"]','{"temp":"15-16°","carafe":"Carafage léger","verre":"Bourgogne"}','{"founded":1993,"owner":"Yves Canarelli","surface":"20 ha","terroir":"Granit et arène granitique, Figari","desc":"Chef de file du renouveau corse. Cépages endémiques, amphore."}'),

('Opus One','','USA','Napa Valley','rouge','#520F1B','[{"n":"Cabernet Sauvignon","p":79},{"n":"Merlot","p":7},{"n":"Cabernet Franc","p":7},{"n":"Petit Verdot","p":5},{"n":"Malbec","p":2}]',14.5,500,2028,2045,'["cassis","mûre","cerise noire","violette","réglisse","chêne neuf","café"]','["Côte de bœuf","Filet mignon","Cheddar vieilli"]','{"temp":"17-18°","carafe":"Carafage 1h","verre":"Bordeaux XL"}','{"founded":1979,"owner":"Constellation Brands & Famille Rothschild","surface":"60 ha","terroir":"Alluvions profondes, Oakville","desc":"Joint-venture entre Baron Philippe de Rothschild et Robert Mondavi."}'),

('Catena Zapata','Adrianna Vineyard Mundus Bacillus Terrae','Argentine','Mendoza','rouge','#520E1A','[{"n":"Malbec","p":100}]',14.5,280,2028,2045,'["cassis","mûre","cerise noire","violette","poivre noir","graphite","cèdre"]','["Bœuf argentin","Empanadas","Provolone fumé"]','{"temp":"16-17°","carafe":"Carafage 1h","verre":"Bordeaux XL"}','{"founded":1902,"owner":"Famille Catena Zapata","surface":"5 ha","terroir":"Altitude 1500m, sols calcaires","desc":"Le vignoble le plus haut de Mendoza. Laura Catena pousse le Malbec vers la haute précision."}'),

('Domaine de Fontsainte','Gris de Gris','Languedoc','Corbières','rosé','#F0B098','[{"n":"Grenache Gris","p":60},{"n":"Grenache Noir","p":40}]',12.5,10,2026,2028,'["pamplemousse","pêche","fraise","rose"]','["Salade méditerranéenne","Poisson grillé","Apéritif"]','{"temp":"8-10°","carafe":"Servir direct","verre":"Tulipe"}','{"founded":1971,"owner":"Yves Laboucarie","surface":"40 ha","terroir":"Argilo-calcaire, Boutenac","desc":"Le Gris de Gris est un rosé de pressurage direct iconique des Corbières."}'),

('Domaine Henry Pellé','Menetou-Salon Morogues','Loire','Menetou-Salon','blanc','#D5C44A','[{"n":"Sauvignon Blanc","p":100}]',12.5,15,2026,2031,'["pamplemousse","citron","groseille","genêt","silex","fumée"]','["Crottin de Chavignol","Poisson de Loire","Asperges"]','{"temp":"10-12°","carafe":"Servir direct","verre":"Sauvignon"}','{"founded":1950,"owner":"Anne Pellé","surface":"41 ha","terroir":"Calcaires kimméridgiens, Morogues","desc":"Alternative qualitative à Sancerre, souvent à moitié prix. Sols kimméridgiens identiques."}'),

('Dom Pérignon','Vintage','Champagne','Champagne','effervescent','#D4B896','[{"n":"Chardonnay","p":52},{"n":"Pinot Noir","p":48}]',12.5,210,2026,2040,'["brioche","agrumes","amande","craie","noisette"]','["Homard","Caviar","Risotto au parmesan"]','{"temp":"8-10°","carafe":"Non","verre":"Flûte évasée"}','{"founded":1668,"owner":"LVMH","surface":"variable","terroir":"Assemblage Grands Crus","desc":"Icône du champagne de prestige. Vincent Chaperon chef de cave."}'),

('E. Guigal','La Mouline','Rhône','Côte-Rôtie','rouge','#5A1020','[{"n":"Syrah","p":89},{"n":"Viognier","p":11}]',14.5,420,2028,2050,'["olive noire","violette","lard fumé","poivre","cacao"]','["Lièvre à la royale","Pigeon aux truffes"]','{"temp":"17-18°","carafe":"Carafage 2h minimum","verre":"Bourgogne XL"}','{"founded":1946,"owner":"Famille Guigal","surface":"60 ha","terroir":"Schistes et gneiss, Côte Brune","desc":"La La de Guigal. Probablement la plus grande Syrah au monde."}')

ON CONFLICT (name, cuvee, region) DO NOTHING;
